name: KingdomEvent
version: '${version}'
main: com.liphium.snowsplash.Snowsplash
api-version: '26.2'

commands:
  set:
    description: "Set a location."
  timer:
    description: "Configure the timer."
